# Extra industry sectors + niche industry pages for Reelclip SEO.
# Each niche gets its own page at /industries/<slug>. Edit copy here, then run tools/build_seo.py

NEW_SECTORS = [
 dict(slug="corporate-enterprise", name="Corporate, Enterprise + Professional Services",
  title="Corporate + Professional Services Video Production in Seattle | Reelclip",
  desc="Video production for enterprises, law firms, B2B, fintech, startups and AI companies in Seattle and Bellevue: brand films, recruiting, conferences and launches.",
  h1="Video for corporate, enterprise + professional services",
  lede="Law firms, B2B companies, fintech, startups and AI teams: video that makes complex businesses feel human and credible.",
  intro=["Professional services sell trust. The right video shows the people, the thinking and the results behind the business, in a way a website paragraph can't.",
         "We bring commercial polish to recruiting films, founder stories, product explainers, conference coverage and launch campaigns, and we're used to working through enterprise approvals and brand guidelines."],
  makes=["Brand and culture films","Founder and leadership stories","Recruiting and employer brand video","Product and platform explainers","Conference and keynote coverage","Customer testimonial films","Investor and launch videos","LinkedIn and paid social content"],
  work=["turbotax-three-event-campaign","chilean-salmon-culinary-event-film","turbotax-tax-season-promo"],
  services=["corporate-video-production","brand-films","event-videography","commercial-video-production"],
  faqs=[("Can you work within our brand guidelines and approval process?","Yes. We plan review rounds around your stakeholders and follow your brand, legal and compliance requirements."),
        ("Do you film at offices?","Yes. Compact crews, quiet setups and schedules built around your team's day.")],
  cities=["seattle","bellevue","redmond","kirkland","bothell"]),
 dict(slug="real-estate-design", name="Real Estate, Architecture + Design",
  title="Real Estate, Architecture + Design Video Production | Reelclip",
  desc="Cinematic video for residential and commercial real estate, luxury properties, architecture firms, interior designers, builders and coworking spaces in Washington.",
  h1="Video for real estate, architecture + design",
  lede="Luxury listings, developments, architecture, interiors and workspaces, filmed so people can feel the space before they visit.",
  intro=["Spaces sell on light, flow and feeling. We plan the walk-through, time the light and use gimbal and drone so a property or project reads as a story, not a slideshow.",
         "From a single luxury listing to a development launch, an architecture portfolio piece or a coworking brand film, we make space-driven video that works on listing sites, social and your own website."],
  makes=["Luxury listing films","Development and pre-sale campaigns","Architecture and interiors portfolio films","Builder and construction progress video","Coworking and workspace brand films","Drone and aerial property video","Agent and team brand videos","Vertical tours for social"],
  work=["lula-coffee-co-brand-film","turbotax-three-event-campaign","gerard-cycles-brand-film"],
  services=["brand-films","commercial-video-production","social-media-video","product-video-production"],
  faqs=[("Do you shoot drone for properties?","Yes. Aerials can be planned into any property or development shoot where the location allows it."),
        ("Can you deliver vertical tours for Instagram and TikTok?","Yes. We frame for vertical on set so listing reels look intentional.")],
  cities=["bellevue","mercer-island","kirkland","seattle","sammamish","gig-harbor"]),
 dict(slug="sports-fitness", name="Sports, Fitness + Recreation",
  title="Sports + Fitness Video Production in Seattle | Teams, Gyms, Pickleball | Reelclip",
  desc="Video production for sports teams, gyms, fitness studios, pickleball clubs, golf courses, cycling brands, athletic apparel and sports events across Washington.",
  h1="Video for sports, fitness + recreation",
  lede="Teams, gyms, studios, clubs, gear and events: video with real movement and energy.",
  intro=["Sport is motion, sweat and sound. We film fast, close and on the move, then cut to the rhythm so the energy comes through on any screen.",
         "We've filmed a TurboTax pickleball activation at Bellevue Pickleball Club and a brand film for Gerard Cycles' hand-built road and gravel bikes, and we bring that same energy to teams, studios and events."],
  makes=["Gym and studio brand films","Membership and class promos","Athlete and coach profiles","Tournament and event recaps","Gear and apparel launches","Sponsor activation coverage","Facility tours","Social content for game days"],
  work=["turbotax-three-event-campaign","gerard-cycles-brand-film","nuwav-jacket-launch-commercial"],
  services=["commercial-video-production","event-videography","social-media-video","product-video-production"],
  faqs=[("Can you film live games and tournaments?","Yes. We cover the action, the crowd and sponsors, and turn recaps around quickly."),
        ("Do you work with gyms and studios on ongoing content?","Yes. Monthly content days work great for class launches, challenges and member stories.")],
  cities=["seattle","bellevue","renton","university-place","kent","tacoma"]),
 dict(slug="health-wellness", name="Healthcare, Wellness + Life Sciences",
  title="Healthcare, Wellness + Biotech Video Production in Washington | Reelclip",
  desc="Video for healthcare organizations, clinics, dental practices, med spas, wellness brands, mental health organizations, health tech and biotech in Washington.",
  h1="Video for healthcare, wellness + life sciences",
  lede="Clinics, practices, med spas, wellness brands, health tech and biotech: warm, clear video that builds trust.",
  intro=["Healthcare and wellness decisions are personal. Patients and partners want to see the people, the space and the care before they book, invest or partner.",
         "We make calm, well-lit, accurate video: practice tours, provider introductions, patient-friendly explainers, recruiting films and research and product stories, handled with care for privacy and consent."],
  makes=["Practice and clinic tours","Provider and team introductions","Treatment and service explainers","Patient-friendly educational video","Recruiting films for clinical teams","Health tech and biotech product stories","Lab and research facility films","Awareness campaign video"],
  work=["chilean-salmon-culinary-event-film","gerard-cycles-brand-film","lula-coffee-co-brand-film"],
  services=["brand-films","corporate-video-production","social-media-video","commercial-video-production"],
  faqs=[("How do you handle patient privacy?","We only film people who have given consent, and we plan shots so no protected information appears on screen."),
        ("Can you explain complex treatments or science simply?","Yes. We use interviews, text animation and simple graphics to make complex topics easy to follow.")],
  cities=["seattle","bothell","bellevue","redmond","tacoma","spokane"]),
 dict(slug="nonprofit-education-public", name="Nonprofits, Education + Public Sector",
  title="Nonprofit, Education + Government Video Production in Washington | Reelclip",
  desc="Video for nonprofits, foundations, universities, schools, community organizations, public health campaigns and government agencies across Washington.",
  h1="Video for nonprofits, education + public sector",
  lede="Foundations, universities, community organizations and public agencies: video that moves people to give, enroll, show up or act.",
  intro=["Mission-driven video has one job: make people care enough to act. We find the human story, keep it honest and make it look as good as any brand campaign.",
         "We filmed a multi-day educational culinary program at the University of Washington for Chilean Salmon and a community-facing TurboTax street-team campaign, and we bring that clarity to fundraising, enrollment and public campaigns."],
  makes=["Fundraising and gala films","Impact and annual report videos","Campus and program films","Educational and training content","Public awareness campaigns","Community event recaps","Donor and volunteer stories","Accessible, captioned versions"],
  work=["chilean-salmon-culinary-event-film","turbotax-tax-season-promo","turbotax-three-event-campaign"],
  services=["brand-films","corporate-video-production","event-videography","social-media-video"],
  faqs=[("Do you offer captioned and accessible versions?","Yes. Captions and accessible versions are part of our post-production."),
        ("Can you work with grant or public procurement timelines?","Yes. We can scope to fixed budgets and provide what your process requires.")],
  cities=["seattle","olympia","tacoma","lacey","spokane","bellingham"]),
 dict(slug="industrial-infrastructure", name="Manufacturing, Industrial + Infrastructure",
  title="Manufacturing + Industrial Video Production in Washington | Reelclip",
  desc="Video for manufacturers, logistics, aerospace and defense, engineering, energy, utilities, agriculture, building materials and trade associations in Washington.",
  h1="Video for manufacturing, industrial + infrastructure",
  lede="Factories, fleets, farms, labs and job sites: cinematic video that makes complex operations look as impressive as they are.",
  intro=["Industrial businesses are full of incredible visuals that nobody outside the gates ever sees. We turn the process, the scale and the people into films that win customers, recruits and trust.",
         "We filmed Gerard Cycles' hand-building process in detail and Chilean Salmon's multi-day educational program, and we're comfortable working around safety protocols, PPE and active operations."],
  makes=["Capabilities and process films","Recruiting films for skilled trades","Facility and plant tours","Safety and training video","Project and infrastructure milestones","Trade show and conference content","Sustainability and impact stories","Drone and aerial site footage"],
  work=["gerard-cycles-brand-film","chilean-salmon-culinary-event-film","jack-s-bbq-commercial-campaign"],
  services=["corporate-video-production","brand-films","production-crew","event-videography"],
  faqs=[("Can you film in active facilities?","Yes. We follow your safety rules and PPE requirements and plan around operations."),
        ("Do you film recruiting videos for skilled trades?","Yes. Showing real people doing real work is one of the best recruiting tools there is.")],
  cities=["kent","everett","renton","fife","sumner","yakima"]),
 dict(slug="travel-tourism", name="Travel, Tourism + Luxury Experiences",
  title="Travel, Tourism + Luxury Experience Video Production | Reelclip",
  desc="Video for travel brands, tourism and destination marketing, hotels and resorts, adventure tourism, yacht and private jet experiences across Washington.",
  h1="Video for travel, tourism + luxury experiences",
  lede="Destinations, hotels, adventures and luxury experiences, filmed so people start planning the trip.",
  intro=["Travel video sells a feeling before it sells a booking. We capture the place, the people and the moments that make an experience worth the trip.",
         "From exotic car rentals with Zadart to nightlife at Sarajevo and a three-day Laid Back Allure weekend, we know how to make an experience look unforgettable."],
  makes=["Destination and tourism campaigns","Hotel and resort films","Adventure and outdoor experience video","Luxury experience promos","Drone and aerial landscapes","Itinerary and travel guide content","Seasonal campaign video","Social content for bookings"],
  work=["zadart-exotic-car-campaign","sarajevo-mariah-the-scientist","laid-back-allure-weekend-recap"],
  services=["commercial-video-production","brand-films","social-media-video","event-videography"],
  faqs=[("Do you travel for destination shoots?","Yes. We shoot across Washington and travel farther by arrangement, with travel built into a clear quote."),
        ("Can you capture aerials?","Yes. Drone and FPV can be planned into destination shoots where permitted.")],
  cities=["leavenworth","seattle","gig-harbor","bellingham","yakima","woodinville"]),
 dict(slug="luxury-lifestyle", name="Luxury, Beauty + Lifestyle Brands",
  title="Luxury, Beauty + Lifestyle Brand Video Production | Reelclip",
  desc="Video for luxury fashion, jewelry, watches, fragrance, eyewear, spas, med spas, salons, barbershops and lifestyle brands in Seattle and Washington.",
  h1="Video for luxury, beauty + lifestyle brands",
  lede="Jewelry, watches, fragrance, eyewear, spas, salons and lifestyle brands: detail-obsessed video that feels as premium as the product.",
  intro=["Luxury lives in the details: the light on a stone, the texture of a fabric, the pour of a fragrance. We shoot macro, style every frame and grade for richness.",
         "Our work with Peristera, NuWav and Zadart shows how we treat products and people with a premium eye, and we bring that to beauty, wellness and lifestyle brands."],
  makes=["Product and macro films","Campaign and lookbook video","Spa and salon brand films","Behind-the-craft stories","Launch teasers","Influencer and creator content","Retail and boutique films","Vertical content for every drop"],
  work=["peristera-first-collection-launch","nuwav-jacket-launch-commercial","zadart-exotic-car-campaign","lula-coffee-co-brand-film"],
  services=["product-video-production","commercial-video-production","social-media-video","brand-films"],
  faqs=[("Can you shoot small products in macro?","Yes. Jewelry, watches, fragrance and accessories get dedicated macro and lighting setups."),
        ("Do you work with salons, spas and med spas?","Yes. Space tours, treatment explainers and social content for appointments and memberships.")],
  cities=["seattle","bellevue","kirkland","tacoma","mercer-island"]),
]

# (name, sector slug, one-line pitch, three specific video ideas)
NICHES = [
 # food + beverage
 ("Restaurants","food-beverage","Restaurant video that fills tables: the food, the room and the people who make it.",["Signature dish films","Opening and new-menu promos","Chef and owner stories"]),
 ("Fine Dining","food-beverage","Slow, elegant video for fine dining that matches the care on the plate.",["Tasting-menu films","Chef's-table stories","Private dining and events promos"]),
 ("Breweries & Distilleries","food-beverage","Brewery, distillery and spirits video, from the grain and the barrel to the pour, including tequila and craft spirits brands.",["Brewing and distilling process films","Release and bottle launch videos","Taproom and tasting-room promos"]),
 ("Coffee Shops & Cafés","food-beverage","Cafe video that makes people want to walk in, like our film for Lula Coffee Co.",["Cafe brand films","Drink and menu content","New location openings"]),
 ("Hotels & Resorts","travel-tourism","Hotel and resort films that sell the stay: rooms, amenities, dining and the feeling of arriving.",["Property brand films","Room and amenity tours","Wedding and event venue promos"]),
 ("Catering Companies","food-beverage","Catering video that shows the spread, the service and the events you make happen.",["Event highlight reels","Menu and station showcases","Wedding and corporate catering promos"]),
 ("Food Manufacturers","food-beverage","Food production video that shows quality, safety and scale from the line to the shelf.",["Process and facility films","Product launch videos","Retail and distributor content"]),
 ("Culinary Events","food-beverage","Culinary event coverage like our Chilean Salmon program: chef demos, talks and the crowd.",["Chef demo recaps","Food festival highlights","Educational culinary films"]),
 ("Hospitality Groups","hospitality-nightlife","One partner for a group's restaurants, bars and venues, with a consistent look across every brand.",["Group brand films","Multi-venue content batches","Openings and seasonal campaigns"]),
 # fashion + luxury + lifestyle
 ("Luxury Fashion","luxury-lifestyle","Luxury fashion films with editorial styling and a premium grade.",["Collection films","Lookbook video","Runway and presentation coverage"]),
 ("Jewelry & Accessories","luxury-lifestyle","Jewelry and accessories video shot in macro so every detail sparkles.",["Macro product films","Bridal and engagement campaigns","Behind-the-bench craft stories"]),
 ("Spas & Wellness","luxury-lifestyle","Spa and wellness video that feels calm and inviting before guests arrive.",["Spa tours","Treatment explainers","Membership promos"]),
 ("Eyewear","luxury-lifestyle","Eyewear video that shows the frames, the fit and the style.",["Collection launches","Try-on content","Optical boutique films"]),
 ("Fashion Designers","fashion-apparel","Films for independent designers that show the vision and the craft behind the collection.",["Designer profiles","Collection launch films","Studio and process stories"]),
 ("Footwear & Sneakers","fashion-apparel","Sneaker and footwear content with culture, like our Sneaker Con coverage for TurboTax.",["Drop and release videos","Customization and craft content","Sneaker event coverage"]),
 ("Fragrance & Perfume","luxury-lifestyle","Fragrance films that make a scent visible through mood, color and texture.",["Launch films","Macro pour and bottle shots","Campaign stories"]),
 ("Barbershops & Salons","luxury-lifestyle","Barbershop and salon video that shows the skill, the vibe and the transformations.",["Shop brand films","Before-and-after content","Stylist and barber profiles"]),
 ("Lifestyle Brands","luxury-lifestyle","Lifestyle brand content that sells the world around the product.",["Brand world films","Creator collaborations","Seasonal campaigns"]),
 ("Watches & Luxury Goods","luxury-lifestyle","Watch and luxury goods films with precision lighting and macro detail.",["Macro product films","Heritage and craft stories","Boutique launches"]),
 ("Luxury Retail","retail-brands","Luxury retail video that brings the in-store experience to every screen.",["Boutique brand films","Product showcases","VIP event coverage"]),
 ("Shopping Centers & Malls","retail-brands","Video for shopping centers and malls: openings, seasonal campaigns and events that drive foot traffic.",["Seasonal campaigns","New tenant openings","Event and activation recaps"]),
 ("Pet Products","retail-brands","Pet product video with real pets, real personality and products front and center.",["Product launches","Pet-and-owner lifestyle content","Social ad sets"]),
 # automotive + transport
 ("Car Dealerships","automotive","Dealership video for inventory, service and brand, built to sell cars online.",["Inventory walkarounds","Dealership brand films","Service department promos"]),
 ("Vehicle Customization","automotive","Wrap, tint, audio and build-shop video that shows the transformation.",["Build and reveal films","Before-and-after content","Shop brand videos"]),
 ("Yacht & Boat Rentals","travel-tourism","Yacht and boat rental video on the water, from the deck and from the air.",["Charter experience films","Drone and on-water footage","Fleet showcases"]),
 ("Luxury Car Rentals","automotive","Exotic and luxury rental promos like our Lamborghini campaign for Zadart.",["Fleet promos","Rolling and FPV drone shots","Experience and event videos"]),
 ("Automotive Brands","automotive","Car launch and brand films with rolling shots, aerials and music-video energy.",["Launch and reveal films","Product feature videos","Brand campaigns"]),
 ("Auto Detailing","automotive","Detailing and ceramic-coating video that makes the finish shine on screen.",["Process and transformation reels","Shop brand films","Package explainers"]),
 ("Bicycle Brands","sports-fitness","Bike brand films like our website hero film for Gerard Cycles.",["Brand and hero films","Product and frame detail","Ride and lifestyle footage"]),
 ("Aviation & Private Jets","travel-tourism","Private aviation video for charters, FBOs and aircraft brands.",["Charter experience films","Aircraft showcases","Aerial and hangar footage"]),
 ("Automotive Events","automotive","Car shows, meets and launches, covered with energy and fast turnaround.",["Car show recaps","Launch and reveal events","Meet and cruise highlights"]),
 # corporate + professional
 ("Law Firms","corporate-enterprise","Law firm video that builds trust: attorneys, practice areas and client stories.",["Firm brand films","Attorney introductions","Practice area explainers"]),
 ("Professional Services","corporate-enterprise","Video for accounting, consulting and advisory firms that makes expertise feel approachable.",["Firm brand films","Thought leadership video","Client testimonials"]),
 ("Startups & Venture-Backed Brands","corporate-enterprise","Startup video for launches, fundraising and hiring, built to move fast and scale.",["Launch videos","Investor and demo-day films","Recruiting and culture content"]),
 ("B2B Brands","corporate-enterprise","B2B video that explains what you do and why it matters, without the jargon.",["Product explainers","Customer case-study films","Trade show content"]),
 ("Recruitment & Staffing","corporate-enterprise","Recruiting and staffing video that attracts candidates and clients.",["Employer brand films","Day-in-the-life videos","Recruiter introductions"]),
 ("Fintech & Financial Services","corporate-enterprise","Fintech and financial services video that makes money products clear and trustworthy, like our TurboTax work.",["Product explainers","Brand and trust films","Campaign and activation coverage"]),
 ("Real Estate Development","real-estate-design","Development video for pre-sales, investors and grand openings.",["Pre-sale campaigns","Construction milestone films","Grand opening coverage"]),
 ("Business Conferences","corporate-events","Conference video: keynotes, panels, sponsors and the recap everyone shares after.",["Keynote and session edits","Sponsor coverage","Highlight recaps"]),
 ("AI & Emerging Technology","corporate-enterprise","Video for AI and emerging tech companies that makes new technology understandable and human.",["Product launch films","Founder and team stories","Demo and explainer videos"]),
 # events + entertainment
 ("Brand Activations","corporate-events","Brand activation coverage like our three-event TurboTax campaign, delivered in a week.",["Activation recaps","Attendee interviews","Sponsor and booth coverage"]),
 ("Experiential Marketing","corporate-events","Experiential campaigns captured so the experience reaches far more people than attended.",["Pop-up and installation films","Multi-city activation recaps","Social-first event content"]),
 ("Live Entertainment","music-entertainment","Live shows, performances and entertainment venues, captured with the energy of the room.",["Show recaps","Venue promos","Performer content"]),
 ("Conventions & Trade Shows","corporate-events","Convention and trade show video, from booth content to full show recaps.",["Booth and product demos","Show floor recaps","Interviews and testimonials"]),
 ("Private Events","hospitality-nightlife","Private events, parties and celebrations, filmed discreetly and edited beautifully.",["Event highlight films","Same-week recaps","Guest interviews"]),
 ("Concerts & Music Festivals","music-entertainment","Concert and festival coverage, like Mariah The Scientist at Sarajevo.",["Performance recaps","Festival highlight films","Backstage and artist content"]),
 ("Art Exhibitions & Galleries","music-entertainment","Gallery and exhibition video that brings artwork and openings to a wider audience.",["Exhibition films","Artist interviews","Opening night recaps"]),
 ("Community Events","nonprofit-education-public","Community event coverage that celebrates the people and the purpose.",["Event recaps","Community stories","Sponsor thank-you videos"]),
 ("Event Production Companies","corporate-events","A reliable video partner for event producers and agencies, including crew for hire.",["Client event recaps","Sizzle reels for your portfolio","Multi-camera event crews"]),
 ("Music Artists & Record Labels","music-entertainment","Music videos and release content for artists and labels, from Seattle to Tacoma.",["Official music videos","Release teasers","Live and backstage content"]),
 ("Influencers & Content Creators","music-entertainment","Cinematic production for creators who want to level up their content and brand deals.",["Brand partnership content","Channel trailers","Creator brand films"]),
 # real estate + design
 ("Residential Real Estate","real-estate-design","Listing and agent video that sells homes faster and builds an agent's brand.",["Listing films","Agent brand videos","Neighborhood guides"]),
 ("Interior Design Studios","real-estate-design","Interior design films that show the finished space and the thinking behind it.",["Portfolio project films","Designer profiles","Before-and-after reveals"]),
 ("Construction Companies","real-estate-design","Construction video for capabilities, recruiting and project milestones.",["Capabilities films","Time-lapse and milestone video","Recruiting content"]),
 ("Commercial Real Estate","real-estate-design","Commercial real estate video for leasing, investors and property marketing.",["Property and leasing films","Drone and aerial tours","Investor presentations"]),
 ("Architecture Firms","real-estate-design","Architecture films that capture light, material and form, built for awards and new business.",["Project portfolio films","Firm brand films","Award submission video"]),
 ("Luxury Properties","real-estate-design","Luxury property films with cinematic movement, golden-hour light and aerials.",["Estate films","Lifestyle property video","Vertical luxury tours"]),
 ("Coworking Spaces","real-estate-design","Coworking video that sells the space, the community and the membership.",["Space tours","Member stories","Event and community content"]),
 # sports + fitness
 ("Professional Sports Teams","sports-fitness","Team content for game days, sponsors, community programs and fans.",["Game-day content","Sponsor activations","Player and community stories"]),
 ("Fitness & Gym Brands","sports-fitness","Gym brand video with sweat, sound and energy that drives memberships.",["Gym brand films","Class and program promos","Member transformation stories"]),
 ("Pickleball & Racket Sports","sports-fitness","Pickleball and racket sports video, like our TurboTax activation at Bellevue Pickleball Club.",["Club brand films","Tournament recaps","Clinic and coaching content"]),
 ("Cycling & Bicycle Companies","sports-fitness","Cycling video on the road and in the shop, like our Gerard Cycles hero film.",["Ride films","Product and build detail","Event and race content"]),
 ("Fitness Studios","sports-fitness","Boutique fitness studio content for classes, instructors and community.",["Studio brand films","Instructor profiles","Class promos"]),
 ("Golf Courses & Clubs","sports-fitness","Golf course and club films with sweeping aerials and the feel of the round.",["Course flyovers","Membership films","Tournament and event recaps"]),
 ("Sports Events & Tournaments","sports-fitness","Tournament and sports event coverage, from opening ceremony to the final whistle.",["Tournament recaps","Athlete interviews","Sponsor coverage"]),
 ("Athletic Apparel","fashion-apparel","Athletic apparel campaigns that show performance and style, in motion.",["Collection launches","Athlete campaigns","Product feature videos"]),
 ("Adventure & Tourism","travel-tourism","Adventure and outdoor tourism video that makes people want to get out there.",["Experience films","Drone and outdoor footage","Seasonal campaigns"]),
 ("Sports Equipment","sports-fitness","Sports equipment video that shows the gear performing where it matters.",["Product launches","In-action demos","Athlete testimonials"]),
 ("Martial Arts & Boxing","sports-fitness","Martial arts and boxing gym video with intensity, discipline and community.",["Gym brand films","Fight and event recaps","Coach and fighter profiles"]),
 ("Sporting Events & Sponsorships","sports-fitness","Sponsorship activation video that proves the value of the partnership.",["Sponsor activation recaps","Fan engagement content","Partnership reports"]),
 # health + wellness
 ("Dental Practices","health-wellness","Dental practice video that puts patients at ease before they book.",["Practice tours","Dentist introductions","Treatment explainers"]),
 ("Education & Training","nonprofit-education-public","Educational and training video that's clear, engaging and easy to follow.",["Course and training modules","Instructor-led video","Program promos"]),
 ("Med Spas & Aesthetics","health-wellness","Med spa and aesthetics video that builds trust and fills the appointment book.",["Treatment explainers","Provider introductions","Spa tours and social content"]),
 ("Wellness Brands","health-wellness","Wellness brand video that feels calm, credible and real.",["Product launches","Founder stories","Lifestyle content"]),
 ("Universities & Colleges","nonprofit-education-public","Campus video for admissions, programs and events, like our work at the University of Washington.",["Campus and program films","Student stories","Event coverage"]),
 ("Nonprofits & Foundations","nonprofit-education-public","Nonprofit and foundation films that inspire giving and show impact.",["Impact films","Gala and fundraiser videos","Donor stories"]),
 ("Travel Brands","travel-tourism","Travel brand campaigns that sell the trip before the booking.",["Destination campaigns","Experience films","Social booking content"]),
 # industrial + infrastructure
 ("Building Materials","industrial-infrastructure","Building materials video that shows quality, installs and finished projects.",["Product and install videos","Project showcases","Trade show content"]),
 ("Community Development","nonprofit-education-public","Community development video that shows the people and places being built up.",["Project stories","Community voices","Milestone and opening films"]),
 ("Manufacturing & Industrial","industrial-infrastructure","Manufacturing video that shows the precision, the people and the scale.",["Capabilities films","Process and line footage","Recruiting video"]),
 ("Logistics & Supply Chain","industrial-infrastructure","Logistics and supply chain video for fleets, warehouses and ports.",["Operations films","Fleet and facility video","Recruiting content"]),
 ("Agriculture & Farming","industrial-infrastructure","Farm and agriculture video from field to market, including Washington's orchards, hops and vineyards.",["Farm and grower stories","Harvest and process films","Brand and product content"]),
 ("Government & Public Agencies","nonprofit-education-public","Clear, accessible video for government agencies and public programs.",["Public information video","Program explainers","Community outreach content"]),
 ("Utilities & Public Services","industrial-infrastructure","Utility and public service video for safety, programs and community trust.",["Safety campaigns","Infrastructure project films","Customer program explainers"]),
 ("Engineering & Infrastructure","industrial-infrastructure","Engineering and infrastructure films that show complex projects coming together.",["Project milestone films","Drone and site footage","Capabilities videos"]),
 ("Energy & Sustainability","industrial-infrastructure","Energy and sustainability video that makes impact tangible.",["Project and impact films","Technology explainers","Sustainability reports in video"]),
 ("Environmental Organizations","nonprofit-education-public","Environmental video that connects people to the places and causes worth protecting.",["Campaign films","Field and conservation stories","Donor and volunteer content"]),
 ("Tourism & Destination Marketing","travel-tourism","Destination marketing video that puts a city or region on the map.",["Destination campaigns","Event and festival content","Local business stories"]),
 ("Defense & Aerospace","industrial-infrastructure","Aerospace and defense contractor video for capabilities, recruiting and programs.",["Capabilities films","Recruiting video","Facility and program content"]),
 ("Trade Associations","industrial-infrastructure","Trade association video for members, advocacy and annual conferences.",["Member value films","Conference coverage","Advocacy campaigns"]),
 ("Luxury Experiences","travel-tourism","Luxury experience video for private tours, concierge services and once-in-a-lifetime moments.",["Experience films","Client stories","Social content for bookings"]),
 ("Public Health Campaigns","nonprofit-education-public","Public health video that's clear, trustworthy and made to reach real communities.",["Awareness campaigns","Educational explainers","Community voices"]),
 ("Healthcare Organizations","health-wellness","Healthcare video for hospitals and health systems: care, people and recruiting.",["Patient story films","Recruiting video","Service line explainers"]),
 ("Medical Clinics","health-wellness","Medical clinic video that helps patients choose you with confidence.",["Clinic tours","Provider introductions","Service explainers"]),
 ("Research Institutions","health-wellness","Research institution films that make discoveries understandable and fundable.",["Research stories","Lab and facility films","Donor and grant video"]),
 ("Health Technology","health-wellness","Health tech video that explains the product and the impact on patients and providers.",["Product explainers","Customer stories","Launch films"]),
 ("Community Organizations","nonprofit-education-public","Video for community organizations that shows the work and the people behind it.",["Program films","Event coverage","Volunteer and member stories"]),
 ("Mental Health Organizations","health-wellness","Thoughtful, respectful video for mental health organizations and services.",["Awareness campaigns","Service explainers","Provider introductions"]),
 ("Biotechnology","health-wellness","Biotech video for investors, partners and recruits, like the life-science hub in Bothell.",["Science and pipeline explainers","Lab and team films","Investor and recruiting video"]),
]

# Items from the master list that already have a dedicated page elsewhere (name -> path)
ALIASES = {"Food & Beverage Brands":"/industries/food-beverage","Fashion & Apparel":"/industries/fashion-apparel",
           "Automotive & Exotic Cars":"/industries/automotive","Retail & Consumer Brands":"/industries/retail-brands",
           "Corporate & Enterprise":"/industries/corporate-enterprise","Corporate Events":"/industries/corporate-events",
           "Product Launches":"/services/product-video-production"}

# City business keywords -> niche names (weaves niches into city pages)
KEYWORDS = [
 ("restaurant",["Restaurants","Hospitality Groups"]),("cafe",["Coffee Shops & Cafés"]),("franchise",["Restaurants"]),
 ("brewer",["Breweries & Distilleries"]),("winer",["Breweries & Distilleries"]),("distiller",["Breweries & Distilleries"]),("spirit",["Breweries & Distilleries"]),("wine",["Breweries & Distilleries"]),("beverage",["Breweries & Distilleries"]),("hops",["Agriculture & Farming","Breweries & Distilleries"]),
 ("food",["Food Manufacturers"]),("tech",["AI & Emerging Technology","Startups & Venture-Backed Brands","B2B Brands"]),("startup",["Startups & Venture-Backed Brands"]),("software",["B2B Brands"]),("gaming",["Live Entertainment"]),
 ("real estate",["Residential Real Estate","Luxury Properties"]),("development",["Real Estate Development"]),("builder",["Construction Companies"]),("construction",["Construction Companies"]),("home services",["Construction Companies"]),
 ("healthcare",["Healthcare Organizations","Medical Clinics"]),("clinic",["Medical Clinics"]),("medical",["Medical Clinics","Health Technology"]),("wellness",["Wellness Brands","Spas & Wellness"]),("health",["Healthcare Organizations"]),
 ("biotech",["Biotechnology","Research Institutions"]),("life science",["Biotechnology"]),
 ("aerospace",["Defense & Aerospace"]),("defense",["Defense & Aerospace"]),("military",["Defense & Aerospace"]),("veteran",["Defense & Aerospace"]),("aviation",["Aviation & Private Jets"]),
 ("manufactur",["Manufacturing & Industrial"]),("logistic",["Logistics & Supply Chain"]),("warehous",["Logistics & Supply Chain"]),("trucking",["Logistics & Supply Chain"]),("port",["Logistics & Supply Chain"]),("distribution",["Logistics & Supply Chain"]),("wholesale",["Logistics & Supply Chain"]),("cargo",["Logistics & Supply Chain"]),
 ("retail",["Shopping Centers & Malls","Luxury Retail"]),("shopping",["Shopping Centers & Malls"]),("outlet",["Shopping Centers & Malls"]),("boutique",["Luxury Retail","Lifestyle Brands"]),("luxury",["Luxury Retail","Luxury Properties"]),
 ("event",["Event Production Companies","Private Events"]),("venue",["Private Events","Live Entertainment"]),("performing arts",["Live Entertainment"]),("festival",["Concerts & Music Festivals"]),("fair",["Community Events"]),("arena",["Sports Events & Tournaments"]),
 ("sports",["Professional Sports Teams","Sports Events & Tournaments"]),("fitness",["Fitness & Gym Brands","Fitness Studios"]),("golf",["Golf Courses & Clubs"]),("recreation",["Adventure & Tourism"]),("outdoor",["Adventure & Tourism","Sports Equipment"]),("equestrian",["Sports Events & Tournaments"]),
 ("education",["Universities & Colleges","Education & Training"]),("nonprofit",["Nonprofits & Foundations"]),("community",["Community Organizations"]),("institution",["Research Institutions"]),("government",["Government & Public Agencies"]),("association",["Trade Associations"]),
 ("music",["Music Artists & Record Labels","Concerts & Music Festivals"]),("nightlife",["Live Entertainment"]),("arts",["Art Exhibitions & Galleries"]),("galler",["Art Exhibitions & Galleries"]),("museum",["Art Exhibitions & Galleries"]),("entertainment",["Live Entertainment"]),
 ("hotel",["Hotels & Resorts"]),("lodging",["Hotels & Resorts"]),("tourism",["Tourism & Destination Marketing","Travel Brands"]),("travel",["Travel Brands"]),("conference",["Business Conferences"]),("meeting",["Business Conferences"]),
 ("automotive",["Car Dealerships","Auto Detailing"]),("dealer",["Car Dealerships"]),("auto shop",["Vehicle Customization","Auto Detailing"]),("fleet",["Logistics & Supply Chain"]),
 ("marine",["Yacht & Boat Rentals"]),("maritime",["Yacht & Boat Rentals"]),("boating",["Yacht & Boat Rentals"]),
 ("agricultur",["Agriculture & Farming"]),("farm",["Agriculture & Farming"]),("orchard",["Agriculture & Farming"]),
 ("fashion",["Fashion Designers","Footwear & Sneakers"]),("streetwear",["Footwear & Sneakers","Fashion Designers"]),("family",["Community Events","Pet Products"]),("kids",["Community Events"]),
 ("professional services",["Professional Services","Law Firms"]),("corporate",["Professional Services","Business Conferences"]),("headquarters",["B2B Brands","Recruitment & Staffing"]),("medical devices",["Health Technology"]),("wedding",["Private Events","Catering Companies"]),("casino",["Live Entertainment"]),("international",["Restaurants"]),
]
