# Content for Reelclip's static SEO pages. Edit copy here, then run: python3 tools/build_seo.py
SITE = "https://reel-clip.com"
EMAIL = "thereelclip@gmail.com"

# Portfolio: internal slug (from index.html data) -> public URL slug + SEO framing
WORK_SEO = {
  "turbotax-three-event-campaign": dict(url="turbotax-event-video-production", title="TurboTax Event Video Production in Seattle + Bellevue", h2="Corporate event videography + production management", services=["event-videography","production-crew","commercial-video-production"], industries=["corporate-events","retail-brands"], cities=["seattle","bellevue"], feature=1),
  "chilean-salmon-culinary-event-film": dict(url="chilean-salmon-event-video", title="Chilean Salmon Culinary Event + Educational Film in Seattle", h2="Corporate event video, interviews + educational production", services=["event-videography","corporate-video-production","brand-films"], industries=["food-beverage","corporate-events"], cities=["seattle"], feature=2),
  "nuwav-jacket-launch-commercial": dict(url="nuwav-jacket-launch-commercial", title="NuWav Jacket Launch Commercial | Seattle Fashion Video", h2="Fashion commercial + clothing launch campaign", services=["commercial-video-production","product-video-production","social-media-video"], industries=["fashion-apparel"], cities=[], feature=3),
  "peristera-first-collection-launch": dict(url="peristera-clothing-launch-campaign", title="Peristera Clothing Launch Campaign + Reels", h2="Apparel product launch films + social ads", services=["product-video-production","social-media-video","commercial-video-production"], industries=["fashion-apparel"], cities=[], feature=4),
  "gerard-cycles-brand-film": dict(url="gerard-cycles-brand-film", title="Gerard Cycles Brand Film | Website Hero Video, Kirkland WA", h2="Brand film, product cinematography + drone", services=["brand-films","product-video-production"], industries=["retail-brands"], cities=["bellevue"], feature=5),
  "jack-s-bbq-commercial-campaign": dict(url="jacks-bbq-restaurant-commercial", title="Jack's BBQ Restaurant Commercial | Seattle Food Video", h2="Restaurant commercial + food videography", services=["commercial-video-production","social-media-video"], industries=["food-beverage","hospitality-nightlife"], cities=["seattle"], feature=6),
  "lula-coffee-co-brand-film": dict(url="lula-coffee-cafe-promo-video", title="Lula Coffee Co. Cafe Promo Video | Seattle Hospitality Video", h2="Cafe + hospitality promotional video", services=["brand-films","social-media-video"], industries=["food-beverage","hospitality-nightlife"], cities=["seattle"], feature=7),
  "zadart-exotic-car-campaign": dict(url="zadart-exotic-car-promo-video", title="Zadart Exotic Car Promo Video | Automotive + FPV Drone, Seattle", h2="Automotive promo, exotic car cinematography + FPV drone", services=["commercial-video-production","social-media-video","product-video-production"], industries=["automotive"], cities=["seattle"], feature=8),
  "turbotax-tax-season-promo": dict(url="turbotax-tax-season-promo", title="TurboTax Tax-Season Street Promo Video | Renton WA", h2="Brand activation promo + street-team coverage", services=["commercial-video-production","event-videography"], industries=["retail-brands","corporate-events"], cities=["renton"], feature=9),
  "laid-back-allure-weekend-recap": dict(url="laid-back-allure-event-recap", title="Laid Back Allure Weekend Event Recap | Seattle Nightlife Video", h2="Multi-day event + nightlife videography", services=["event-videography","social-media-video"], industries=["hospitality-nightlife","music-entertainment"], cities=["seattle"], feature=10),
  "sarajevo-mariah-the-scientist": dict(url="mariah-the-scientist-sarajevo-event-recap", title="Mariah The Scientist at Sarajevo | Seattle Concert + Nightlife Recap", h2="Concert, nightlife + celebrity appearance recap", services=["event-videography","social-media-video"], industries=["hospitality-nightlife","music-entertainment","automotive"], cities=["seattle"], feature=11),
  "saint-meadow-can-t-complain": dict(url="saint-meadow-cant-complain-music-video", title="Saint Meadow – Can't Complain | Official Music Video", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=[]),
  "tbg-kam-bino-my-life": dict(url="tbg-kam-bino-my-life-music-video", title="TBG Kam Bino – My Life | Music Video", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=[]),
  "youngcam206-ruthless": dict(url="youngcam206-ruthless-music-video", title="YoungCam206 – Ruthless | Seattle Rap Music Video", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=[]),
  "rell-moore-chrome-hearts": dict(url="rell-moore-chrome-hearts-music-video", title="Rell Moore – Chrome Hearts | Black + White Seattle Music Video", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=["seattle"]),
  "tha-baby-street-runner": dict(url="tha-baby-street-runner-music-video", title="Tha Baby – Street Runner | Music Video at the Washington State Fair", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=["puyallup"]),
  "slotlifebaby-different-time": dict(url="slotlifebaby-different-time-music-video", title="SlotLifeBaby – Different Time | Tacoma Music Video", h2="Music video direction + production", services=["music-videos"], industries=["music-entertainment"], cities=["tacoma","spanaway"]),
}

SERVICES = [
 dict(slug="commercial-video-production", name="Commercial Video Production", short="Commercials + campaigns",
  title="Commercial Video Production in Seattle | Ads + Campaigns | Reelclip",
  desc="Seattle commercial video production for brand campaigns, ads and launches. Concept, crew, filming, editing and color, delivered for TV, web and social.",
  h1="Commercial video production in Seattle",
  lede="Commercials and campaigns with a point of view, built for the screens your customers actually watch: social feeds, paid ads, your website and the big screen.",
  intro=["Reelclip creates commercials for brands that want to be remembered, not scrolled past. We start with what you're selling, who it's for and how it should feel, then build the concept, the shot list and the crew around that.",
         "Some clients come with a finished creative direction and need a production team to execute it. Others come with a product and a deadline. Either way, you get one team that takes it from idea to final delivery, with every cutdown and aspect ratio your campaign needs."],
  includes=["Creative concept + scripting","Mood boards, storyboards + shot lists","Casting + talent coordination","Location scouting + permits guidance","Cinema camera, lighting + audio crew","Drone + FPV aerials when the story needs them","Editing, color grading + sound design","Cutdowns for 6s, 15s, 30s + vertical"],
  deliverables=["Hero commercial (15–60s)","Vertical cutdowns for Reels, TikTok + Shorts","Paid-social ad variations","Website + YouTube versions","Behind-the-scenes stills"],
  steps=[("Discovery","We learn the product, audience, goal and budget, and agree on what success looks like."),("Concept + plan","Treatment, mood board, script, shot list, schedule and crew, approved before we roll."),("Production","A tight, organized shoot day with the right crew size for the job."),("Post + delivery","Edit, color, sound and every cutdown, with clear review rounds.")],
  work=["nuwav-jacket-launch-commercial","jack-s-bbq-commercial-campaign","zadart-exotic-car-campaign","peristera-first-collection-launch"],
  faqs=[("How much does a commercial cost in Seattle?","It depends on crew size, shoot days, locations, talent and how many deliverables you need. A focused social-first spot and a multi-day campaign with talent, aerials and a dozen cutdowns are very different budgets. Tell us your budget and we'll design the strongest version that fits it."),
        ("Do you write the concept, or do we?","Both work. We can develop the full creative from scratch, or execute a concept your team or agency already has."),
        ("Can you deliver versions for every platform?","Yes. We plan coverage for vertical and horizontal from the start, so every cutdown looks intentional, not cropped."),
        ("How long does a commercial take?","Most projects take two to six weeks from kickoff to final delivery. Rush timelines are possible; our TurboTax package delivered three videos in one week.")],
  related=["product-video-production","brand-films","social-media-video"]),
 dict(slug="brand-films", name="Brand Films", short="Brand films",
  title="Brand Film Production in Seattle | Reelclip",
  desc="Cinematic brand films for Seattle and Washington businesses: website hero videos, founder stories and about-us films that show who you are.",
  h1="Brand film production in Seattle",
  lede="Visual storytelling that shows the people, personality and purpose behind your business, made to live at the top of your website and travel everywhere else.",
  intro=["A brand film is the video that explains why you exist without sounding like an ad. It's the hero on your homepage, the first thing investors see, the clip your team shares when they're proud of where they work.",
         "We build brand films from the ground up when there's no style guide yet, or match an established look when there is. For Gerard Cycles we created the visual language from scratch, from mood board to color, and delivered a 60-second hero film for their new website."],
  includes=["Brand discovery + story development","Founder and team interviews","Visual identity, mood board + storyboard","Multi-day shoots + drone","Product and process cinematography","Music licensing + sound design","Color grading to your brand palette"],
  deliverables=["Website hero film (30–90s)","Long-form story cut (2–4 min)","Looping silent homepage version","Social teasers + vertical cuts","Stills for web and press"],
  steps=[("Story","We interview you and find the one idea the film is about."),("Look","Mood board, palette, locations and shot list that fit your brand."),("Shoot","People, places and process, filmed with care and minimal disruption."),("Finish","Edit, color and versions for your site, socials and pitch decks.")],
  work=["gerard-cycles-brand-film","lula-coffee-co-brand-film","chilean-salmon-culinary-event-film"],
  faqs=[("What's the difference between a brand film and a commercial?","A commercial sells a specific product or offer. A brand film builds trust in who you are, so it keeps working for years on your website, in pitches and in hiring."),
        ("Do we need a script?","Not necessarily. Many brand films are built from interviews and observed moments. We'll recommend scripted, documentary or a hybrid based on your story."),
        ("Can you make a silent version for our homepage?","Yes. We deliver a lightweight, looping, no-audio version designed to autoplay as a website hero.")],
  related=["commercial-video-production","corporate-video-production","product-video-production"]),
 dict(slug="product-video-production", name="Product Video Production", short="Product launches",
  title="Product Video Production + Launch Videos in Seattle | Reelclip",
  desc="Product launch videos, e-commerce clips and social ads for Seattle and Washington brands. Styled product cinematography that sells on your site and in feeds.",
  h1="Product video production + launch campaigns",
  lede="Product films and short-form assets that make people want the thing, designed for launch day, your product pages and paid social.",
  intro=["Launching something new? We plan the hero film, the teasers and the always-on assets together, so your launch has a consistent look from the first teaser to the last retargeting ad.",
         "We've filmed an apparel brand's first collection, a streetwear jacket launch, a bike brand's hero film and an exotic car rental campaign. Each one got a different approach, because a jacket and a Lamborghini shouldn't be filmed the same way."],
  includes=["Launch campaign planning","Styled product + macro cinematography","Lifestyle scenes with real people","Studio or on-location setups","E-commerce and product-page clips","Motion graphics + text animation"],
  deliverables=["Launch hero film","Teasers + countdown clips","Product-page loops","Paid social ad set","Vertical reels per product or look"],
  steps=[("Launch plan","Map every asset to a launch moment: teaser, drop day and after."),("Styling","Props, sets, wardrobe and talent that fit your audience."),("Shoot","Hero, detail and lifestyle coverage in one efficient schedule."),("Roll-out","Edits sized and paced for every placement.")],
  work=["peristera-first-collection-launch","nuwav-jacket-launch-commercial","gerard-cycles-brand-film","zadart-exotic-car-campaign"],
  faqs=[("Can you shoot multiple products in one day?","Yes. We build the schedule around your product list so you get the most usable assets per shoot day."),
        ("Do you provide models or talent?","We can cast talent, or feature your community. NuWav's launch starred local creatives instead of models, and it fit the brand perfectly."),
        ("Can you make ads in multiple versions for testing?","Yes. We plan alternate hooks, lengths and calls-to-action so your team can A/B test.")],
  related=["commercial-video-production","social-media-video","brand-films"]),
 dict(slug="event-videography", name="Event Videography", short="Events + activations",
  title="Event Videography in Seattle | Corporate Events + Recaps",
  desc="Seattle event videography for corporate events, brand activations, conferences, concerts and nightlife. Recaps, interviews, photography and fast turnaround.",
  h1="Event videography in Seattle",
  lede="Corporate events, brand activations, concerts and nightlife, captured as they happen and cut into recaps people actually finish watching.",
  intro=["Live events don't give second takes. We show up with a shot list, a plan for audio and enough crew to be in the right place when the moment happens. Then we turn it around fast, because recaps matter most while the event is still being talked about.",
         "We've covered a three-event TurboTax campaign (delivered in one week), a multi-day Chilean Salmon culinary program at the University of Washington and a Seattle hotel venue, Mariah The Scientist at Sarajevo and a full Laid Back Allure weekend."],
  includes=["Event recap films","On-site interviews + testimonials","Mic setup + live audio capture","Multi-camera crews for larger events","Event photography","Same-week and rush delivery","Brand activation + sponsor coverage"],
  deliverables=["Highlight recap (60–90s)","Vertical recaps for social","Interview + testimonial clips","Full-length session recordings","Edited event photo gallery"],
  steps=[("Run of show","We review your schedule, sponsors and must-have moments."),("Crew plan","The right number of shooters, audio and photo for the room."),("Event day","Coverage of the program, the people and the brand."),("Fast turnaround","Recaps delivered while the buzz is still fresh.")],
  work=["turbotax-three-event-campaign","chilean-salmon-culinary-event-film","sarajevo-mariah-the-scientist","laid-back-allure-weekend-recap"],
  faqs=[("How fast can we get our event recap?","Turnaround depends on scope, and we can move fast: for TurboTax, all three event recaps were delivered inside one week."),
        ("Can you cover multiple events or locations?","Yes. We hire and direct additional videographers when events overlap or run across several venues."),
        ("Do you record interviews and testimonials?","Yes. We bring microphones and set up clean audio for interviews, presenters and live demos."),
        ("Do you also take photos?","Yes. Event photography can be added to any video package.")],
  related=["production-crew","social-media-video","corporate-video-production"]),
 dict(slug="social-media-video", name="Social Media Video", short="Social content",
  title="Social Media Video Production in Seattle | Reels + TikTok | Reelclip",
  desc="Vertical and horizontal social media video for Seattle brands: Reels, TikTok, Shorts and paid social ads, shot cinematically and built to stop the scroll.",
  h1="Social media video production",
  lede="Cinematic vertical and horizontal content for Reels, TikTok, Shorts and paid social, made to hold attention in the first second.",
  intro=["Social content has to earn attention fast, and it has to keep coming. We shoot for vertical from the start, write hooks into the edit and plan batches so you leave one shoot day with weeks of posts.",
         "For Peristera we delivered a launch film plus five stylized reels, one for each look. For Laid Back Allure we cut vertical stories from the weekend's events, including the all-white party and the patio."],
  includes=["Vertical-first shooting","Hook-driven editing","Batch content days","Captions + on-screen text","Trend-aware formats","Paid social ad variations"],
  deliverables=["Reels / TikToks / Shorts","Story sequences","Ad creative sets","Monthly content batches","Thumbnails + covers"],
  steps=[("Content plan","Pillars, formats and a posting calendar."),("Batch shoot","Many posts captured in one efficient day."),("Edit","Hooks, pacing, captions and sound for each platform."),("Repeat","Monthly batches that keep your feed consistent.")],
  work=["peristera-first-collection-launch","laid-back-allure-weekend-recap","zadart-exotic-car-campaign","lula-coffee-co-brand-film"],
  faqs=[("Can you make monthly content for us?","Yes. Ongoing content partnerships are one of the best ways to work with us; see our partnerships page."),
        ("Do you post for us?","We focus on production and editing and deliver ready-to-post files. We're happy to work alongside your social team or agency."),
        ("Can you shoot vertical and horizontal at the same time?","Yes. We frame for both on set so nothing feels cropped later.")],
  related=["content-partnerships","product-video-production","event-videography"]),
 dict(slug="corporate-video-production", name="Corporate Video Production", short="Corporate video",
  title="Corporate Video Production in Seattle | Reelclip",
  desc="Corporate video production in Seattle and the Eastside: recruiting films, executive messages, educational videos, conference content and internal communications.",
  h1="Corporate video production in Seattle",
  lede="Recruiting films, executive messages, educational and training content, and conference video that still feels like it was made by people with taste.",
  intro=["Corporate video doesn't have to look corporate. We bring the same cinematic eye we use for commercials to the videos your company makes for employees, partners and recruits.",
         "For Chilean Salmon we filmed chef demonstrations, educational talks and interviews across multiple days and venues, and delivered a 1:42 film with text animations that made the information easy to follow."],
  includes=["Recruiting + culture films","Executive and leadership messages","Training + educational video","Conference and keynote coverage","Interview lighting + clean audio","Motion graphics for data and key points"],
  deliverables=["Polished hero video","Internal comms cuts","Training modules","Conference session edits","Captioned, accessible versions"],
  steps=[("Brief","Goals, audiences, approvals and brand guidelines."),("Pre-production","Scripts, interview questions, schedules and locations."),("Filming","Low-disruption shoots at your office, venue or on location."),("Review + deliver","Structured review rounds that fit your approval process.")],
  work=["chilean-salmon-culinary-event-film","turbotax-three-event-campaign","gerard-cycles-brand-film"],
  faqs=[("Can you film at our office without disrupting work?","Yes. We plan compact setups and schedules around your team's day."),
        ("Can you add captions and graphics?","Yes. Captions, lower thirds, text animation and simple motion graphics are part of our post-production."),
        ("Do you work with procurement and vendor onboarding?","Yes. We're used to working with marketing teams at larger organizations and can provide what your vendor process needs.")],
  related=["event-videography","brand-films","content-partnerships"]),
 dict(slug="music-videos", name="Music Videos", short="Music videos",
  title="Music Video Production in Seattle + Tacoma | Reelclip",
  desc="Seattle and Tacoma music video production: concept, direction, cinematography, editing and color for artists, with a portfolio of official videos across Washington.",
  h1="Music video production in Seattle + Tacoma",
  lede="Concept, direction, cinematography, editing and color for artists who want their video to look as good as the record sounds.",
  intro=["Music videos are where Reelclip's style was built. We've shot at the Washington State Fair, in Seattle lobbies and on escalators, and on late-night streets in Tacoma and Spanaway.",
         "We collaborate on the concept or bring yours to life, then handle the shoot, edit and color. That range is why brands hire us too: it shows we can make something with personality."],
  includes=["Concept development + treatment","Location scouting","Direction + cinematography","Lighting + practical effects","Editing + color grading","Release cutdowns for social"],
  deliverables=["Official music video","Vertical teasers + snippets","Thumbnail stills","Behind-the-scenes content"],
  steps=[("Treatment","The idea, the look and the locations."),("Prep","Schedule, crew, wardrobe and gear."),("Shoot","Performance and story coverage."),("Release","Final video plus teasers for rollout.")],
  work=["saint-meadow-can-t-complain","rell-moore-chrome-hearts","slotlifebaby-different-time","tha-baby-street-runner","youngcam206-ruthless","tbg-kam-bino-my-life"],
  faqs=[("How much is a music video?","Budgets vary with locations, crew and shoot days. Share your budget and we'll recommend the strongest concept for it."),
        ("Do you shoot outside Seattle?","Yes. We've shot in Tacoma, Spanaway and at the Washington State Fair in Puyallup, and travel across Washington."),
        ("Can you help with the concept?","Yes. Some artists bring a full vision; others want us to develop the treatment with them.")],
  related=["social-media-video","commercial-video-production"]),
 dict(slug="production-crew", name="Production Crew + Support", short="Crew + support",
  title="Video Production Crew for Hire in Seattle | Reelclip",
  desc="Hire a Seattle video production crew: videographers, producers, audio and editors for agencies and brands that already have the creative and need flawless execution.",
  h1="Video production crew for hire in Seattle",
  lede="For agencies and marketing teams that already have the creative direction and need a reliable team to shoot, direct crews and deliver on deadline.",
  intro=["Sometimes the idea is done and what you need is execution. Reelclip can produce and direct the shoot, hire and brief additional videographers and editors, and manage the workflow from footage to final delivery.",
         "For TurboTax, Reelclip worked as Production Director across three activations: hiring the crew, assigning each event, filming two of them, and coordinating post so all three videos landed within a week."],
  includes=["Production direction + coordination","Videographers and camera operators","Audio capture and mic setup","Editors and post-production management","Crew hiring and briefing","Client communication and delivery management"],
  deliverables=["Footage delivered to your specs","Edits to your agency's brief","Organized media handoff","On-site production management"],
  steps=[("Brief","Your creative, shot list, specs and deadlines."),("Crew","We assemble and brief the right people."),("Execute","On-site direction and real-time problem solving."),("Hand off","Organized footage or finished edits, on time.")],
  work=["turbotax-three-event-campaign","turbotax-tax-season-promo","chilean-salmon-culinary-event-film"],
  faqs=[("Can you scale the crew for bigger shoots?","Yes. We regularly hire and direct additional videographers, photographers and editors for multi-location work."),
        ("Do you work under our agency's brand?","Yes. We're comfortable working as your production partner behind the scenes."),
        ("Can you deliver raw footage only?","Yes, or fully edited pieces. We'll match whatever your team needs.")],
  related=["event-videography","corporate-video-production","content-partnerships"]),
 dict(slug="content-partnerships", name="Ongoing Content Partnerships", short="Ongoing partnerships",
  title="Ongoing Video Content Partnerships for Brands | Reelclip",
  desc="A recurring video production partner for Seattle and Washington brands: monthly content, seasonal campaigns, event coverage and launches from one consistent team.",
  h1="An ongoing video partner for your brand",
  lede="A launch might be the first project. It doesn't have to be the last. Work with one consistent team for campaigns, seasons, events and everything after.",
  intro=["The brands that get the most from video don't hire a new crew every time. They build a relationship with a team that already knows the look, the people and the approval process, so every project starts faster and lands stronger.",
         "Reelclip partners with businesses that need regular campaign content, monthly social batches, event coverage and product updates. You get a planned calendar, predictable budgeting and a team that gets better at your brand every month."],
  includes=["Quarterly creative planning","Monthly content production days","Seasonal campaign shoots","Event coverage on call","Priority scheduling","A consistent look across every asset"],
  deliverables=["Monthly social content batches","Quarterly campaign films","Event recaps as they happen","Asset library for your team"],
  steps=[("Plan the year","Map launches, seasons and events into a content calendar."),("Set the rhythm","Monthly or quarterly production days you can count on."),("Produce","Shoots planned in batches for efficiency."),("Improve","Review what performs and refine each cycle.")],
  work=["turbotax-three-event-campaign","laid-back-allure-weekend-recap","peristera-first-collection-launch"],
  faqs=[("How does a partnership work?","We agree on a regular schedule and scope, like a monthly content day plus seasonal campaigns, and plan production ahead so you always have fresh content."),
        ("Is it cheaper than one-off projects?","Usually it's more efficient: batching shoots and keeping one team reduces planning time and gives you more assets per dollar."),
        ("Can we pause or change the plan?","Yes. Partnerships are built around your calendar and can flex with your business.")],
  related=["social-media-video","event-videography","commercial-video-production"]),
]

INDUSTRIES = [
 dict(slug="food-beverage", name="Food, Beverage + Spirits", title="Food, Beverage + Tequila Brand Video Production | Reelclip",
  desc="Video production for restaurants, cafes, breweries, wineries and spirits brands, including tequila and craft liquor, across Seattle and Washington.",
  h1="Video for food, beverage + spirits brands",
  lede="Restaurants, cafes, breweries, wineries and spirits brands, from tequila and mezcal to craft whiskey, filmed so people can almost taste it.",
  intro=["Food and drink live or die on texture, light and appetite appeal. We plan for the pour, the sizzle and the first sip, then build the people and the place around them.",
         "We've filmed Jack's BBQ's pitmaster at the smoker, Lula Coffee Co.'s pink cafe and signature drinks, and Chilean Salmon's chef demonstrations. For spirits and tequila brands we bring the same approach to product launches, bar programs, brand activations and distributor content, following your responsible-marketing guidelines and casting talent of legal drinking age."],
  makes=["Restaurant + cafe commercials","Menu and dish cinematography","Cocktail, pour + bar program videos","Spirits and tequila product launches","Brand activations, tastings + pop-ups","Winery, brewery + distillery stories","Chef and founder profiles","Social content for new menus and seasons"],
  work=["jack-s-bbq-commercial-campaign","lula-coffee-co-brand-film","chilean-salmon-culinary-event-film","sarajevo-mariah-the-scientist"],
  services=["commercial-video-production","social-media-video","event-videography","product-video-production"],
  faqs=[("Do you work with tequila and spirits brands?","Yes. We produce launch films, cocktail and bar content, activations and distributor videos for spirits brands, and follow your brand's responsible-marketing and talent-age requirements."),
        ("Can you film during service hours?","We can, with a compact crew, but most food content looks best when we schedule hero shots before or after service.")],
  cities=["seattle","woodinville","tacoma","bellevue","yakima","tumwater"]),
 dict(slug="fashion-apparel", name="Fashion + Apparel", title="Fashion + Apparel Video Production in Seattle | Reelclip",
  desc="Fashion and apparel video production in Seattle: clothing launch campaigns, lookbook films, streetwear commercials and social reels for every drop.",
  h1="Fashion + apparel video production",
  lede="Launch films, lookbooks and streetwear campaigns that sell the clothes and the culture around them.",
  intro=["Clothing brands need more than nice footage. They need the fit, the fabric and the attitude in every frame, plus enough content to keep the drop going after launch day.",
         "We launched NuWav's newest jacket through Seattle creatives instead of models, and built Peristera's first collection into one campaign film plus five stylized reels, one per look."],
  makes=["Collection launch films","Lookbook + campaign videos","Streetwear commercials","Product detail + fit videos","Model and creator content","Reels for every look"],
  work=["nuwav-jacket-launch-commercial","peristera-first-collection-launch"],
  services=["product-video-production","commercial-video-production","social-media-video"],
  faqs=[("Can you shoot a full collection in one day?","Usually, yes. We schedule by look and location to get hero, detail and social coverage efficiently."),
        ("Do you cast models?","We can cast models or feature creators from your community, depending on your brand.")],
  cities=["seattle","bellevue","tacoma"]),
 dict(slug="automotive", name="Automotive + Exotic Cars", title="Automotive + Exotic Car Video Production in Seattle | Reelclip",
  desc="Automotive video production for dealerships, exotic car rentals and auto brands in Seattle: rolling shots, FPV drone and social-first car commercials.",
  h1="Automotive + exotic car video production",
  lede="Rolling shots, FPV drone and music-video energy for dealerships, rental fleets, detailers and car brands.",
  intro=["Cars are made to move, so we film them moving. Car-to-car rolling footage, low angles and FPV drone passes put the viewer in the driver's seat.",
         "For Zadart we built a music-video-inspired campaign for two Lamborghinis around Seattle, with aerial and FPV drone by Cris City, and paced the edit to hook viewers in the first seconds."],
  makes=["Dealership and inventory videos","Exotic and luxury rental promos","Car launch and reveal films","Detailing and wrap shop content","Rolling and FPV drone shots","Social ads for every vehicle"],
  work=["zadart-exotic-car-campaign","sarajevo-mariah-the-scientist"],
  services=["commercial-video-production","social-media-video","product-video-production"],
  faqs=[("Do you do FPV drone?","Yes. We work with specialist FPV pilots for close, high-speed tracking shots."),
        ("Can you film on public roads?","We plan routes and timing for safe rolling shots and can advise on what permits a location requires.")],
  cities=["seattle","bellevue","kent","tacoma","lynnwood"]),
 dict(slug="corporate-events", name="Corporate Events + Brand Activations", title="Corporate Event + Brand Activation Video in Seattle | Reelclip",
  desc="Corporate event and brand activation video in Seattle and Bellevue: grand openings, conferences, pop-ups and multi-event campaigns, delivered fast.",
  h1="Corporate event + brand activation video",
  lede="Grand openings, conferences, pop-ups and sponsorships, covered with a plan and delivered fast.",
  intro=["Event agencies and marketing teams need a crew that follows the shot list, captures sponsors and still finds the real moments. We do both.",
         "For TurboTax we directed coverage of Sneaker Con, a Bellevue pickleball activation and a Bellevue grand opening, with a crew of three videographers and an editor, and delivered all three recaps within one week."],
  makes=["Grand opening and launch recaps","Conference and keynote video","Pop-ups and experiential activations","Sponsorship and booth coverage","Attendee interviews + testimonials","Multi-event campaign packages"],
  work=["turbotax-three-event-campaign","chilean-salmon-culinary-event-film","turbotax-tax-season-promo"],
  services=["event-videography","production-crew","corporate-video-production"],
  faqs=[("Can you cover several activations at once?","Yes. We scale the crew and direct multiple videographers across venues."),
        ("How quickly can we post recaps?","We can deliver priority recaps within days so you can post while the event is still trending.")],
  cities=["seattle","bellevue","redmond","tukwila","seatac","federal-way"]),
 dict(slug="hospitality-nightlife", name="Hospitality + Nightlife", title="Bar, Nightlife + Hospitality Video in Seattle | Reelclip",
  desc="Video production for Seattle bars, lounges, nightclubs, hotels, venues and event promoters: promos, event recaps and social content that sells the night.",
  h1="Hospitality + nightlife video",
  lede="Bars, lounges, clubs, hotels and promoters: promo videos and recaps that make people want to be there next time.",
  intro=["Nightlife moves fast and the lighting is never easy. We shoot handheld and flexible, read the room, and grade the footage so it looks as good as it felt.",
         "We've filmed Mariah The Scientist's night at Sarajevo, a three-day Laid Back Allure weekend and Lula Coffee Co.'s pink cafe interiors."],
  makes=["Venue and bar promo videos","Event and party recaps","Artist appearance coverage","Hotel and space tours","Weekly social content","Promoter sizzle reels"],
  work=["sarajevo-mariah-the-scientist","laid-back-allure-weekend-recap","lula-coffee-co-brand-film","jack-s-bbq-commercial-campaign"],
  services=["event-videography","social-media-video","brand-films"],
  faqs=[("Can you film in dark venues?","Yes. Low-light nightlife is a big part of our portfolio, and our grade keeps footage consistent across changing lights."),
        ("Do you work with promoters on recurring events?","Yes. Recurring event coverage works well as an ongoing partnership.")],
  cities=["seattle","tacoma","bellevue","auburn","everett"]),
 dict(slug="music-entertainment", name="Music + Entertainment", title="Music + Entertainment Video Production in Washington | Reelclip",
  desc="Music videos, concert recaps and artist content in Seattle, Tacoma and across Washington. Direction, cinematography, editing and color.",
  h1="Music + entertainment video",
  lede="Official music videos, concert recaps and artist content, made by a team that started in music.",
  intro=["Our music work is where the Reelclip look comes from: bold concepts, real locations and a grade with personality.",
         "Six official music videos, from the Washington State Fair to Seattle lobbies to late-night Tacoma, plus nightlife and concert recaps."],
  makes=["Official music videos","Concert and tour recaps","Artist appearances","Album rollout teasers","Live performance video","Behind-the-scenes content"],
  work=["saint-meadow-can-t-complain","rell-moore-chrome-hearts","slotlifebaby-different-time","sarajevo-mariah-the-scientist"],
  services=["music-videos","event-videography","social-media-video"],
  faqs=[("Do you work with independent artists?","Yes. Most of our music videos are with independent Washington artists."),
        ("Can you cover a concert or show?","Yes. We film performances, crowds and backstage for recaps and social.")],
  cities=["seattle","tacoma","puyallup","spanaway"]),
 dict(slug="retail-brands", name="Retail, Consumer + Growing Brands", title="Retail + Consumer Brand Video Production | Reelclip",
  desc="Video for retail stores, consumer brands and growing businesses in Washington: launches, store openings, brand films and recurring social content.",
  h1="Video for retail + consumer brands",
  lede="Store openings, product drops, brand films and the steady stream of content growing brands need.",
  intro=["Consumer brands need video at every stage: the launch, the opening, the seasonal campaign and the everyday content in between.",
         "We've filmed TurboTax's Bellevue store opening and tax-season street team, and Gerard Cycles' hero film for a hand-built bike brand in Kirkland."],
  makes=["Store opening recaps","Brand and founder films","Seasonal campaigns","Product launch videos","Website and e-commerce video","Recurring social content"],
  work=["turbotax-three-event-campaign","gerard-cycles-brand-film","turbotax-tax-season-promo","peristera-first-collection-launch"],
  services=["brand-films","product-video-production","content-partnerships"],
  faqs=[("Can you film in our store during open hours?","Yes, with a small crew. For hero shots we usually schedule before opening."),
        ("Do you work with startups?","Yes. We right-size productions for growing businesses and scale up as you grow.")],
  cities=["bellevue","tukwila","lynnwood","auburn","kirkland"]),
]

# Cities. tier: home = core metro, regular = regular drive, travel = by arrangement
# angle: what makes this city distinct for video. spots: real shoot-location ideas. biz: industries to pitch locally.
CITIES = [
 dict(slug="seattle", name="Seattle", county="King County", tier="home", route="Reelclip is based here",
  angle="Seattle is home base. We've filmed across the city, from Jack's BBQ in SoDo and Lula Coffee Co. to the Sarajevo nightclub in Belltown, Chilean Salmon at the University of Washington and Sneaker Con Seattle.",
  biz=["Tech and startup brands","Restaurants, cafes + bars","Fashion and streetwear","Event agencies + venues","Nonprofits and institutions"],
  spots=["Pike Place Market and the waterfront","Capitol Hill streets and venues","Pioneer Square brick and alleys","SoDo warehouses and studios","South Lake Union glass and steel","Kerry Park skyline views"]),
 dict(slug="bellevue", name="Bellevue", county="King County", tier="home", route="across Lake Washington on I-90 or SR 520",
  angle="Bellevue's downtown is one of the Eastside's busiest business districts, home to T-Mobile's headquarters and a skyline of corporate towers. It's where we covered TurboTax's grand opening and pickleball activation, and filmed Gerard Cycles' brand film.",
  biz=["Corporate and tech companies","Retail and luxury brands","Real estate and development","Restaurants and hospitality","Health and wellness"],
  spots=["Downtown Bellevue towers and plazas","Bellevue Downtown Park","Bellevue Square and Lincoln Square","Meydenbauer Bay waterfront","Eastside offices and showrooms"]),
 dict(slug="redmond", name="Redmond", county="King County", tier="home", route="northeast of Seattle via SR 520",
  angle="Redmond is home to Microsoft and Nintendo of America, plus a growing restaurant and retail scene around Redmond Town Center. Jack's BBQ, one of our commercial clients, has a Redmond location.",
  biz=["Tech companies and teams","Gaming and software","Restaurants and breweries","Fitness and outdoor brands","Startups"],
  spots=["Marymoor Park","Redmond Town Center","Downtown Redmond Central Connector","Sammamish River Trail","Office and campus interiors"]),
 dict(slug="kirkland", name="Kirkland", county="King County", tier="home", route="on the Eastside along I-405",
  angle="Kirkland pairs a Lake Washington waterfront with a strong small-business and tech scene. Gerard Cycles, whose website hero film we produced, hand-builds carbon road and gravel bikes in Kirkland.",
  biz=["Independent and DTC brands","Tech offices","Restaurants and wine bars","Boutique fitness","Marine and outdoor"],
  spots=["Kirkland waterfront and marina","Park Lane and downtown streets","Juanita Beach Park","Cross Kirkland Corridor","Workshops and showrooms"]),
 dict(slug="renton", name="Renton", county="King County", tier="home", route="at the south end of Lake Washington off I-405",
  angle="Renton is home to Boeing's 737 plant and the Seattle Seahawks' training facility, with a busy retail hub at The Landing. We filmed TurboTax's tax-season street-team promo here.",
  biz=["Aerospace and manufacturing","Sports and fitness","Retail and restaurants","Healthcare","Logistics"],
  spots=["Gene Coulon Memorial Beach Park","The Landing","Downtown Renton","Cedar River Trail","Industrial and hangar spaces"]),
 dict(slug="kent", name="Kent", county="King County", tier="home", route="south of Seattle in the Kent Valley",
  angle="The Kent Valley is one of the region's biggest manufacturing and distribution hubs and home to Blue Origin's headquarters, plus the accesso ShoWare Center for sports and concerts.",
  biz=["Manufacturing and aerospace","Warehousing and logistics","Food production","Automotive and fleet","Sports and events"],
  spots=["Kent Station","accesso ShoWare Center","Warehouse and industrial interiors","Green River Trail","Downtown Kent"]),
 dict(slug="federal-way", name="Federal Way", county="King County", tier="home", route="south on I-5 between Seattle and Tacoma",
  angle="Federal Way sits right between Seattle and Tacoma, with the Performing Arts and Event Center, Wild Waves Theme & Water Park and the former Weyerhaeuser campus. It's a natural base for businesses serving both cities.",
  biz=["Event venues and performing arts","Family entertainment","Healthcare and clinics","Restaurants and retail","Real estate"],
  spots=["Performing Arts and Event Center","Town Square Park","Dash Point State Park","Celebration Park","The Commons and Pavilion Center"]),
 dict(slug="tukwila", name="Tukwila", county="King County", tier="home", route="minutes south of Seattle where I-5 meets I-405",
  angle="Tukwila is a retail and business crossroads, anchored by Westfield Southcenter, one of the largest shopping centers in the Pacific Northwest, and minutes from Sea-Tac Airport.",
  biz=["Retail and shopping centers","Hotels near the airport","Restaurants and franchises","Logistics and wholesale","Event spaces"],
  spots=["Westfield Southcenter","Tukwila Station area","Green River Trail","Hotel ballrooms and meeting rooms","Warehouse showrooms"]),
 dict(slug="seatac", name="SeaTac", county="King County", tier="home", route="right next to Sea-Tac Airport off I-5 and SR 518",
  angle="Built around Seattle-Tacoma International Airport, SeaTac is full of hotels, conference rooms and travel businesses, which makes it a hub for corporate meetings, trainings and fly-in events.",
  biz=["Hotels and conference centers","Travel and aviation","Logistics and air cargo","Corporate meetings","Restaurants"],
  spots=["Angle Lake Park","Hotel conference centers","Airport-area meeting spaces","Light rail stations","Industrial and cargo facilities"]),
 dict(slug="auburn", name="Auburn", county="King County", tier="regular", route="south on SR 167",
  angle="Auburn mixes a historic downtown with destination businesses like Emerald Downs racetrack, The Outlet Collection and the Muckleshoot Casino, plus a strong manufacturing base.",
  biz=["Entertainment and gaming","Retail and outlets","Manufacturing","Restaurants","Equestrian and sports"],
  spots=["Emerald Downs","The Outlet Collection","Downtown Auburn","Game Farm Park","Industrial spaces"]),
 dict(slug="issaquah", name="Issaquah", county="King County", tier="regular", route="east on I-90 at the foot of the Issaquah Alps",
  angle="Issaquah is Costco's hometown and the gateway to the Issaquah Alps, so it's equally good for corporate work and outdoor brand stories, with Lake Sammamish right next door.",
  biz=["Corporate headquarters","Outdoor and fitness brands","Healthcare","Restaurants and breweries","Real estate"],
  spots=["Lake Sammamish State Park","Cougar and Tiger Mountain trails","Gilman Village","Downtown Front Street","Issaquah Highlands"]),
 dict(slug="burien", name="Burien", county="King County", tier="home", route="southwest of Seattle near the Sound",
  angle="Burien's walkable Olde Burien district and Puget Sound shoreline make it great for small business, restaurant and lifestyle content with real neighborhood character.",
  biz=["Local restaurants and cafes","Independent retail","Arts and community groups","Healthcare","Real estate"],
  spots=["Olde Burien","Seahurst Park beach","Burien Town Square","Lake Burien area","Waterfront viewpoints"]),
 dict(slug="des-moines", name="Des Moines", county="King County", tier="home", route="south of Sea-Tac along the Sound",
  angle="Des Moines is a waterfront city with a marina and beach park, ideal for lifestyle, real estate and hospitality content with water views.",
  biz=["Marine and boating","Restaurants","Real estate","Community events","Wellness"],
  spots=["Des Moines Marina","Des Moines Beach Park","Saltwater State Park","Marine View Drive","Waterfront restaurants"]),
 dict(slug="shoreline", name="Shoreline", county="King County", tier="home", route="just north of Seattle on I-5",
  angle="Shoreline borders Seattle to the north, with Richmond Beach, new light rail stations and a busy Aurora Avenue business corridor.",
  biz=["Local businesses on Aurora","Healthcare and clinics","Education","Restaurants","Real estate"],
  spots=["Richmond Beach Saltwater Park","Shoreline light rail stations","Aurora corridor businesses","Hamlin Park","Shoreline Community College"]),
 dict(slug="sammamish", name="Sammamish", county="King County", tier="regular", route="on the plateau east of Lake Sammamish",
  angle="Sammamish is a residential plateau with lakefront parks, ideal for lifestyle, real estate, family brands and wellness businesses on the Eastside.",
  biz=["Real estate and builders","Family and kids brands","Wellness and fitness","Home services","Restaurants"],
  spots=["Pine Lake Park","Lake Sammamish shoreline","Sammamish Commons","Soaring Eagle Park","Modern homes and estates"]),
 dict(slug="bothell", name="Bothell", county="King + Snohomish County", tier="regular", route="north on I-405",
  angle="Bothell's Canyon Park area is a hub for biotech and life-science companies, and the city is also home to UW Bothell and a revitalized downtown on Main Street.",
  biz=["Biotech and life sciences","Medical devices","Education","Restaurants and breweries","Tech"],
  spots=["Canyon Park business district","UW Bothell campus","Main Street","Sammamish River Trail","Lab and office interiors"]),
 dict(slug="woodinville", name="Woodinville", county="King County", tier="regular", route="northeast of Seattle in the Sammamish Valley",
  angle="Woodinville is Washington's wine country close to Seattle, with more than 100 wineries and tasting rooms plus breweries and distilleries. It's a perfect fit for beverage, spirits and hospitality brands.",
  biz=["Wineries and tasting rooms","Distilleries and spirits brands","Breweries and cideries","Event venues and weddings","Restaurants"],
  spots=["Hollywood District tasting rooms","Warehouse District wineries","Sammamish River Trail","Vineyard and barrel rooms","Event barns and estates"]),
 dict(slug="mercer-island", name="Mercer Island", county="King County", tier="home", route="in the middle of Lake Washington on I-90",
  angle="Mercer Island's lakefront homes and parks make it a natural setting for luxury real estate, lifestyle and wellness content between Seattle and Bellevue.",
  biz=["Luxury real estate","Wellness and medical","Professional services","Lifestyle brands","Restaurants"],
  spots=["Luther Burbank Park","Lakefront estates","Town Center","Mercer Island waterfront","I-90 lid park"]),
 dict(slug="tacoma", name="Tacoma", county="Pierce County", tier="regular", route="south on I-5",
  angle="Tacoma has its own creative identity, from the Museum of Glass and Chihuly Bridge of Glass to the Port of Tacoma and the Stadium District. We filmed SlotLifeBaby's \"Different Time\" across Tacoma and Spanaway.",
  biz=["Restaurants and breweries","Arts and museums","Port, logistics and maritime","Healthcare","Music and nightlife"],
  spots=["Museum of Glass and Bridge of Glass","Point Defiance Park","Stadium District","Thea Foss Waterway","Tacoma Dome area"]),
 dict(slug="lakewood", name="Lakewood", county="Pierce County", tier="regular", route="south of Tacoma on I-5",
  angle="Lakewood sits next to Joint Base Lewis-McChord and around American Lake, with historic Thornewood Castle and a diverse small-business community.",
  biz=["Veteran-owned businesses","Restaurants and international markets","Healthcare","Event venues","Real estate"],
  spots=["American Lake Park","Thornewood Castle","Fort Steilacoom Park","Lakewood Towne Center","Lakewold Gardens"]),
 dict(slug="puyallup", name="Puyallup", county="Pierce County", tier="regular", route="southeast of Tacoma on SR 167 and SR 512",
  angle="Puyallup is home to the Washington State Fair, where we shot Tha Baby's \"Street Runner\" music video among the rides and neon. It's also a growing city for retail, restaurants and events.",
  biz=["Fairs and large events","Restaurants and breweries","Retail","Agriculture and farms","Real estate"],
  spots=["Washington State Fair grounds","Downtown Puyallup","Pioneer Park","Riverwalk Trail","South Hill shopping"]),
 dict(slug="university-place", name="University Place", county="Pierce County", tier="regular", route="west of Tacoma on the Sound",
  angle="University Place is home to Chambers Bay, the links-style course that hosted the 2015 U.S. Open, with sweeping Puget Sound views made for cinematic brand and golf content.",
  biz=["Golf and recreation","Real estate","Restaurants","Wellness","Event venues"],
  spots=["Chambers Bay","Chambers Bay loop trail","Puget Sound sunset views","Town center","Curran Apple Orchard"]),
 dict(slug="gig-harbor", name="Gig Harbor", county="Pierce County", tier="regular", route="across the Tacoma Narrows Bridge",
  angle="Gig Harbor's working harbor, waterfront restaurants and Mount Rainier views make it ideal for maritime, hospitality and lifestyle stories.",
  biz=["Maritime and boating","Waterfront restaurants","Boutiques and galleries","Real estate","Wineries and breweries"],
  spots=["Gig Harbor waterfront","Tacoma Narrows Bridge views","Harbor History Museum","Skansie Brothers Park","Marinas"]),
 dict(slug="sumner", name="Sumner", county="Pierce County", tier="regular", route="on SR 167 near Puyallup",
  angle="Sumner pairs a small, walkable downtown with one of the valley's busiest industrial and distribution areas, which makes it great for both local business and manufacturing video.",
  biz=["Manufacturing and distribution","Small downtown businesses","Restaurants","Agriculture","Home services"],
  spots=["Downtown Sumner Main Street","Industrial and warehouse facilities","Sumner Link Trail","Riverside parks","Rainier views"]),
 dict(slug="spanaway", name="Spanaway", county="Pierce County", tier="regular", route="south of Tacoma on SR 7",
  angle="We shot part of SlotLifeBaby's \"Different Time\" in Spanaway, where the artist wanted the places he knows best. Its lake, parks and quieter streets give real, local texture.",
  biz=["Local businesses","Military families and veteran-owned businesses","Restaurants","Auto shops","Music artists"],
  spots=["Spanaway Lake Park","Pacific Avenue businesses","Late-night streets","Sprinker Recreation Center","Local parks"]),
 dict(slug="fife", name="Fife", county="Pierce County", tier="regular", route="at the Port of Tacoma off I-5",
  angle="Fife sits next to the Port of Tacoma and along I-5, with logistics, trucking and auto businesses, plus Emerald Queen Casino's entertainment venue.",
  biz=["Logistics and trucking","Automotive dealers","Entertainment and gaming","Restaurants","Manufacturing"],
  spots=["Port of Tacoma views","Emerald Queen Casino","Dealership lots","Warehouse interiors","Dacca Park"]),
 dict(slug="everett", name="Everett", county="Snohomish County", tier="regular", route="north on I-5",
  angle="Everett is home to Boeing's widebody factory, one of the largest buildings in the world by volume, plus a revitalized Port of Everett waterfront and Angel of the Winds Arena.",
  biz=["Aerospace and manufacturing","Healthcare","Restaurants and breweries","Sports and arena events","Maritime"],
  spots=["Port of Everett waterfront","Angel of the Winds Arena","Downtown Everett","Jetty Island","Industrial facilities"]),
 dict(slug="lynnwood", name="Lynnwood", county="Snohomish County", tier="regular", route="north on I-5, now on light rail",
  angle="Lynnwood is a major retail center around Alderwood Mall and a fast-growing city since light rail arrived at Lynnwood City Center in 2024.",
  biz=["Retail and shopping centers","Automotive dealers","Restaurants and franchises","Healthcare","Real estate and new development"],
  spots=["Alderwood Mall","Lynnwood City Center station","Lynndale Park","Highway 99 businesses","New mixed-use developments"]),
 dict(slug="edmonds", name="Edmonds", county="Snohomish County", tier="regular", route="north of Seattle on the Sound",
  angle="Edmonds is a waterfront arts town with a ferry terminal, a walkable downtown and some of the best sunsets on the Sound.",
  biz=["Restaurants and wine bars","Galleries and arts","Boutiques","Wellness","Real estate"],
  spots=["Edmonds waterfront and ferry","Downtown Fifth Avenue","Marina Beach Park","Brackett's Landing","Edmonds Center for the Arts"]),
 dict(slug="mukilteo", name="Mukilteo", county="Snohomish County", tier="regular", route="on the water south of Everett",
  angle="Mukilteo's lighthouse and ferry to Whidbey Island give it postcard waterfront scenery, and it's close to Paine Field's aerospace businesses.",
  biz=["Aerospace suppliers","Waterfront restaurants","Real estate","Tourism","Wellness"],
  spots=["Mukilteo Lighthouse Park","Ferry terminal","Waterfront promenade","Paine Field area","Japanese Gulch"]),
 dict(slug="mill-creek", name="Mill Creek", county="Snohomish County", tier="regular", route="north on I-5 and I-405",
  angle="Mill Creek's town center and planned neighborhoods suit lifestyle, retail and real estate content in south Snohomish County.",
  biz=["Retail and boutiques","Restaurants","Real estate","Fitness","Family services"],
  spots=["Mill Creek Town Center","North Creek Trail","Golf course views","Residential neighborhoods","McCollum Park"]),
 dict(slug="marysville", name="Marysville", county="Snohomish County", tier="travel", route="north of Everett on I-5",
  angle="Marysville sits beside the Tulalip area, home to Tulalip Resort Casino and Seattle Premium Outlets, and is one of Snohomish County's fastest-growing cities.",
  biz=["Retail and outlets","Entertainment","Restaurants","Construction and builders","Healthcare"],
  spots=["Seattle Premium Outlets (Tulalip)","Downtown Marysville","Ebey Waterfront Park","Jennings Park","New developments"]),
 dict(slug="arlington", name="Arlington", county="Snohomish County", tier="travel", route="north on I-5 and SR 530",
  angle="Arlington has a busy municipal airport, aviation and manufacturing businesses, and quick access to the Stillaguamish Valley's farms and rivers.",
  biz=["Aviation and manufacturing","Agriculture and farms","Outdoor recreation","Local businesses","Construction"],
  spots=["Arlington Municipal Airport","Downtown Olympic Avenue","Stillaguamish River","Farmland and barns","Centennial Trail"]),
 dict(slug="olympia", name="Olympia", county="Thurston County", tier="travel", route="south on I-5",
  angle="Washington's capital has a monumental capitol campus, a working port, the Olympia Farmers Market and The Evergreen State College, plus plenty of state agencies and associations.",
  biz=["Government and associations","Nonprofits","Restaurants and breweries","Education","Healthcare"],
  spots=["Washington State Capitol campus","Percival Landing","Olympia Farmers Market","Capitol Lake","Downtown Olympia"]),
 dict(slug="lacey", name="Lacey", county="Thurston County", tier="travel", route="just east of Olympia on I-5",
  angle="Lacey is home to Saint Martin's University and a growing base of logistics, retail and healthcare employers next to Olympia.",
  biz=["Education","Logistics and distribution","Healthcare","Retail","Real estate"],
  spots=["Saint Martin's University","Woodland Creek Community Park","Lacey Town Square","Chehalis Western Trail","Distribution facilities"]),
 dict(slug="tumwater", name="Tumwater", county="Thurston County", tier="travel", route="just south of Olympia on I-5",
  angle="Tumwater is known for Tumwater Falls and the historic Olympia Brewery site, which makes it a fitting place for beverage, craft and heritage brand stories.",
  biz=["Craft beverage","Manufacturing","Government offices","Restaurants","Real estate"],
  spots=["Tumwater Falls Park","Historic brewery district","Pioneer Park","Deschutes River","Olympia Regional Airport area"]),
 dict(slug="bremerton", name="Bremerton", county="Kitsap County", tier="travel", route="a ferry ride from downtown Seattle",
  angle="Bremerton is home to Puget Sound Naval Shipyard and connects to downtown Seattle by ferry, with a revitalized waterfront and arts district.",
  biz=["Maritime and defense contractors","Restaurants","Arts and theater","Healthcare","Real estate"],
  spots=["Bremerton waterfront boardwalk","Seattle-Bremerton ferry","Manette Bridge","Evergreen Park","Downtown arts district"]),
 dict(slug="silverdale", name="Silverdale", county="Kitsap County", tier="travel", route="in central Kitsap",
  angle="Silverdale is Kitsap County's main retail hub around Kitsap Mall, on the shores of Dyes Inlet.",
  biz=["Retail","Restaurants","Healthcare","Automotive dealers","Real estate"],
  spots=["Kitsap Mall area","Silverdale Waterfront Park","Dyes Inlet views","Clear Creek Trail","Old Town Silverdale"]),
 dict(slug="bellingham", name="Bellingham", county="Whatcom County", tier="travel", route="north on I-5 toward Canada",
  angle="Bellingham blends Western Washington University, a craft brewery scene and outdoor access to Mount Baker and Chuckanut Drive.",
  biz=["Breweries and food","Outdoor and gear brands","Education","Tourism","Healthcare"],
  spots=["Chuckanut Drive","Fairhaven historic district","Boulevard Park","Western Washington University","Bellingham Bay waterfront"]),
 dict(slug="leavenworth", name="Leavenworth", county="Chelan County", tier="travel", route="over Stevens Pass on US 2",
  angle="Leavenworth's Bavarian-style village draws visitors year-round for Oktoberfest, Christmas lighting and mountain recreation, ideal for tourism, beverage and destination-event video.",
  biz=["Tourism and lodging","Breweries, wine + spirits","Festivals and events","Restaurants","Outdoor recreation"],
  spots=["Front Street village","Icicle Creek","Waterfront Park","Lodges and resorts","Cascade mountain views"]),
 dict(slug="yakima", name="Yakima", county="Yakima County", tier="travel", route="over Snoqualmie Pass and south on I-82",
  angle="The Yakima Valley grows most of the hops used in American beer and is a major wine region, which makes it a natural destination for beverage, agriculture and brewery stories.",
  biz=["Hops and breweries","Wineries","Agriculture and orchards","Food processing","Tourism"],
  spots=["Hop fields","Wineries and tasting rooms","Orchards","Downtown Yakima","Yakima River Canyon"]),
 dict(slug="spokane", name="Spokane", county="Spokane County", tier="travel", route="across the state on I-90",
  angle="Spokane is Eastern Washington's largest city, with Riverfront Park and Spokane Falls downtown, Gonzaga University and a growing healthcare, food and events scene.",
  biz=["Healthcare","Education","Restaurants and breweries","Events and sports","Manufacturing"],
  spots=["Riverfront Park and Spokane Falls","Downtown Spokane","Gonzaga University","Manito Park","Kendall Yards"]),
 dict(slug="vancouver-wa", name="Vancouver, WA", county="Clark County", tier="travel", route="south on I-5, across the river from Portland",
  angle="Vancouver's new waterfront district, historic Fort Vancouver and fast-growing business community make it a strong market just across the Columbia from Portland.",
  biz=["Real estate and development","Restaurants and wineries","Healthcare","Tech and manufacturing","Retail"],
  spots=["The Waterfront Vancouver","Fort Vancouver National Historic Site","Esther Short Park","Columbia River views","Downtown Main Street"]),
]
